name: Render resume.html & deploy to github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  render-resume-html:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Node Install
      run: npm ci

    - name: Validate JSON
      run: npx resumed validate

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3

    - name: Render Resume HTML
      run: |
        mkdir _site
        npx resumed render resume.json -o _site/index.html

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v1


  deploy-resume-html:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: render-resume-html
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
